baseURL = ""
languageCode = "pt-BR"
DefaultContentLanguage = "pt"
title = "aMostra Estatística"
theme = "meghna-hugo"
summaryLength = 10

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"

# Menu
[menu]
    [[menu.nav]]
    name = "Sobre"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "Apoio"
    URL = "portfolio"
    weight = 6

    [[menu.nav]]
    name = "Inscrições"
    URL = "pricing"
    weight = 8

    [[menu.nav]]
    name = "Programação"
    URL = "services"
    weight = 3

    [[menu.nav]]
    name = "Contato"
    URL = "contact-us"
    weight = 9


# Site params
[params]
home= "Home"
logo = "images/logo.png"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# Meta data
description = "aMostra Estatística 2019"
author = "IME"
# Google Analitycs
googleAnalitycsID = "Your ID"
custom_css = ["css/custom.css"]

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/header.jpg"
    #icon = "tf-ion-play"
    heading = "aMostra Estatística 2019"
    content= "Venha conhecer..."
    btn = true
    btnText="Programação"
    btnURL="#services"

    # footer
    [params.footer]
        copyright = "Themefisher Team"
        copyrightURL = "http://www.themefisher.com"

        # social Icons
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-facebook"
        url = "https://www.facebook.com/aMostraEstatistica/"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-youtube"
        url = "https://www.youtube.com/channel/UCargFh7dj6ZtDcCNlw30F-w"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-instagram"
        url = "#"
